version: '3.8'
services:
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: ./Backend/Arca/
      dockerfile: ./celery_worker/Dockerfile
    env_file:
      - .env
    volumes:
      - backend_media:/django-app/media
      - backend_staticfiles:/django-app/staticfiles
    depends_on:
      - redis
      - backend

  backend:
    build:
      context: ./Backend/Arca/
    ports:
      - "8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=Arca.settings
    volumes:
      - backend_staticfiles:/django-app/staticfiles
      - backend_media:/django-app/media
      - ./Backend/Arca:/django-app

  db:
    image: postgres:15
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  frontend:
    build:
      context: ./Frontend
    volumes:
      - frontend_dist:/react-app/dist
    depends_on:
      - backend

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./Nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - backend_staticfiles:/django-app/staticfiles:ro
      - backend_media:/django-app/media:ro
      - frontend_dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  db_data:
  backend_staticfiles:
    external: false
  backend_media:
    external: false
  frontend_dist:
    external: false
